# Generated by Django 5.2.6 on 2025-10-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(max_length=50)),
                ('codigo_autorizacion', models.CharField(max_length=100)),
            ],
        ),
    ]
