# Generated by Django 5.2.8 on 2025-11-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(default='APROBADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='codigo_autorizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
