# Generated by Django 5.2.8 on 2025-11-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago_estado_alter_pago_codigo_autorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='buy_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
