# Generated by Django 5.2.8 on 2025-11-21 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_pago_buy_order'),
        ('productos', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='buy_order',
            field=models.CharField(default='SIN-ORDEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='codigo_autorizacion',
            field=models.CharField(default='SIN-CODIGO', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pagos.pago')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
