# Generated by Django 5.2.7 on 2025-12-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='boleta_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
