# Generated by Django 5.2.7 on 2025-12-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_pago_boleta_enviada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='buy_order',
            field=models.CharField(default='SIN-ORDEN', max_length=100, unique=True),
        ),
    ]
