# Generated by Django 5.2.8 on 2025-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
