# Generated by Django 5.2.5 on 2025-11-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_codigo_barras_codigobarras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='productos'),
            preserve_default=False,
        ),
    ]
