# Generated by Django 5.2.7 on 2025-12-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_proveedor_remove_producto_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
